# Generated by Django 3.0.2 on 2020-12-19 10:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('open_amount_in_ngn', models.DecimalField(decimal_places=2, max_digits=100)),
                ('high_amount_in_usd', models.DecimalField(decimal_places=2, max_digits=100)),
                ('low_amount_in_usd', models.DecimalField(decimal_places=2, max_digits=100)),
                ('close_amount_in_usd', models.DecimalField(decimal_places=2, max_digits=100)),
                ('volume_amount_in_usd', models.DecimalField(decimal_places=2, max_digits=100)),
                ('deleted', models.BooleanField(default=False)),
                ('data_time', models.DateTimeField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_stock', to='company.Company')),
            ],
            options={
                'ordering': ['date_added'],
            },
        ),
    ]
